server:
  port: 8080

jwt:
  secret-key: 'lingganguliguliguliguajialinggangulinggangu'
  expiration-time: '86400000'

spring:
  application:
    name: manager

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/manager
    username: root
    password: '123321'
  sql:
    init:
      mode: never
      schema-locations: classpath:db/schema.sql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mqtt:
    #MQTT服务地址，端口号默认11883，如果有多个，用逗号隔开
    url: tcp://117.72.63.151:1883
    #用户名
    username: admin
    #密码
    password: public
    #客户端id(不能重复)
    client:
      id: client-id
      providerid: provider-id
      consumerid: consumer-id
    #MQTT默认的消息推送主题，实际可在调用接口是指定
    default:
      topic: topic

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0

ark:
  api:
    key: 05962d59-c5f4-4150-be75-f12f05e5d3d4
    model: doubao-seed-1-6-flash-250615
    temperature: 0.7
    max_tokens: 1024


logging:
  level:
    com.example.homework.mapper: debug

